name: run coverage
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  run:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install .[dev]
      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest
          coverage xml
